version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - travelbuddy-network

  backend:
    build:
      context: ..
      dockerfile: ./travel_planner_ui/server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
    volumes:
      - ./server/logs:/app/logs
    networks:
      - travelbuddy-network
    restart: unless-stopped

networks:
  travelbuddy-network:
    driver: bridge

volumes:
  logs: