substitutions:
  _REGION: us-central1

steps:
  # Build backend image from repo root (Dockerfile references repo paths)
  - name: gcr.io/cloud-builders/docker
    id: Build backend image
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/travelbuddy-backend", "-f", "travel_planner_ui/server/Dockerfile", "."]

  - name: gcr.io/cloud-builders/docker
    id: Push backend image
    args: ["push", "gcr.io/$PROJECT_ID/travelbuddy-backend"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy backend
    entrypoint: bash
    args:
      - -c
      - >-
        gcloud run deploy travelbuddy-backend \
          --image gcr.io/$PROJECT_ID/travelbuddy-backend \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars ENVIRONMENT=production \
          --port 8080

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Get backend URL
    entrypoint: bash
    args:
      - -c
      - >-
        gcloud run services describe travelbuddy-backend \
          --platform managed \
          --region ${_REGION} \
          --format value(status.url) | tee backend_url.txt

  - name: gcr.io/cloud-builders/bash
    id: Write frontend env
    entrypoint: bash
    args:
      - -c
      - >-
        echo "VITE_API_URL=$(cat backend_url.txt)" > travel_planner_ui/.env.production

  # Build frontend image from UI folder
  - name: gcr.io/cloud-builders/docker
    id: Build frontend image
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/travelbuddy-frontend", "-f", "travel_planner_ui/Dockerfile", "travel_planner_ui"]

  - name: gcr.io/cloud-builders/docker
    id: Push frontend image
    args: ["push", "gcr.io/$PROJECT_ID/travelbuddy-frontend"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy frontend
    entrypoint: bash
    args:
      - -c
      - >-
        gcloud run deploy travelbuddy-frontend \
          --image gcr.io/$PROJECT_ID/travelbuddy-frontend \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --memory 256Mi \
          --cpu 1 \
          --max-instances 5 \
          --port 8080

images:
  - gcr.io/$PROJECT_ID/travelbuddy-backend
  - gcr.io/$PROJECT_ID/travelbuddy-frontend

options:
  logging: CLOUD_LOGGING_ONLY
